spring.application.name=studylink

spring.datasource.url=jdbc:mysql://localhost:3006/studylink
spring.datasource.username=root
spring.datasource.password=chaos1990

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true